name: finsire_task1
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.4.4 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.6
  get: 4.6.6
  flutter: 
    sdk: flutter
  http: ^1.2.2

dev_dependencies: 
  flutter_lints: 4.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - assets/images/war_and_peace.jpg
    - assets/images/amy.jpg
    - assets/images/open-book.png
    - assets/images/clock.png
    - assets/images/crown.png
    - assets/images/thunder.png
    - assets/images/idea.png
    - assets/images/checked.png
    - assets/images/cube.png
    - assets/images/like.png
    - assets/images/marked-book.png
    - assets/images/timer.png

